name: Branch protection frontend

on:
  push:
    branches: [main, dev, feature-CI-Sonar]
  pull_request:
    branches: [dev, main]

jobs:
  Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Installeer alle packages
        run: npm i

      - name: Use static code analysis
        run: npm run lint

      - name: Run tests
        run: npm run test_ci
